apiVersion: v1
kind: Pod
metadata:
  name: portfolio-pod
  namespace: portfolio
  labels:
    app: portfolio
spec:
  containers:
  - name: portfolio
    image: suskale/portfolio:latest
    ports:
    - containerPort: 80
  restartPolicy: Always
